/**
 * driveRepository
 * ---------------
 * All SQL for drives + events lives here. Screens/hooks call these functions
 * and never touch SQL directly. Rows are mapped from snake_case columns to
 * camelCase domain objects on the way out.
 */
import type { DrivingEventType } from "@/constants/thresholds";
import type { DrivingEvent } from "@/detection/DetectionEngine";

import { getDb } from "./database";

/** A persisted drive (one completed session). */
export interface DriveRecord {
  id: string;
  startedAt: number; // epoch ms
  endedAt: number; // epoch ms
  durationSec: number;
  distanceKm: number;
  score: number;
  rating: string;
  totalEvents: number;
  aiFeedback: string | null; // populated on Day 4
}

/** A persisted event belonging to a drive. */
export interface StoredEvent {
  id: string;
  driveId: string;
  type: DrivingEventType;
  t: number;
  value: number;
  severity: number;
  deduction: number;
}

/** Aggregate stats for the dashboard. */
export interface DriveStats {
  totalDrives: number;
  averageScore: number; // 0 when there are no drives
}

/** Fields needed to persist a finished drive (id generated by caller). */
export interface NewDrive {
  id: string;
  startedAt: number;
  endedAt: number;
  durationSec: number;
  distanceKm: number;
  score: number;
  rating: string;
  aiFeedback?: string | null;
}

// --- raw row shapes (snake_case, straight from SQLite) ---
type DriveRow = {
  id: string;
  started_at: number;
  ended_at: number;
  duration_sec: number;
  distance_km: number;
  score: number;
  rating: string;
  total_events: number;
  ai_feedback: string | null;
};

type EventRow = {
  id: string;
  drive_id: string;
  type: string;
  t: number;
  value: number;
  severity: number;
  deduction: number;
};

const toDrive = (r: DriveRow): DriveRecord => ({
  id: r.id,
  startedAt: r.started_at,
  endedAt: r.ended_at,
  durationSec: r.duration_sec,
  distanceKm: r.distance_km,
  score: r.score,
  rating: r.rating,
  totalEvents: r.total_events,
  aiFeedback: r.ai_feedback,
});

const toEvent = (r: EventRow): StoredEvent => ({
  id: r.id,
  driveId: r.drive_id,
  type: r.type as DrivingEventType,
  t: r.t,
  value: r.value,
  severity: r.severity,
  deduction: r.deduction,
});

/**
 * Persist a completed drive and all its events in a single transaction.
 * `total_events` is derived from the events array.
 */
export async function saveDrive(
  drive: NewDrive,
  events: DrivingEvent[],
): Promise<void> {
  const db = await getDb();
  await db.withTransactionAsync(async () => {
    await db.runAsync(
      `INSERT INTO drives
         (id, started_at, ended_at, duration_sec, distance_km, score, rating, total_events, ai_feedback)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        drive.id,
        drive.startedAt,
        drive.endedAt,
        drive.durationSec,
        drive.distanceKm,
        drive.score,
        drive.rating,
        events.length,
        drive.aiFeedback ?? null,
      ],
    );

    for (const e of events) {
      await db.runAsync(
        `INSERT INTO events (id, drive_id, type, t, value, severity, deduction)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        [e.id, drive.id, e.type, e.t, e.value, e.severity, e.deduction],
      );
    }
  });
}

/** All drives, newest first. */
export async function listDrives(): Promise<DriveRecord[]> {
  const db = await getDb();
  const rows = await db.getAllAsync<DriveRow>(
    "SELECT * FROM drives ORDER BY started_at DESC",
  );
  return rows.map(toDrive);
}

/** One drive by id (null if missing). */
export async function getDrive(id: string): Promise<DriveRecord | null> {
  const db = await getDb();
  const row = await db.getFirstAsync<DriveRow>(
    "SELECT * FROM drives WHERE id = ?",
    [id],
  );
  return row ? toDrive(row) : null;
}

/** All events for a drive, in chronological order (powers the timeline). */
export async function getDriveEvents(driveId: string): Promise<StoredEvent[]> {
  const db = await getDb();
  const rows = await db.getAllAsync<EventRow>(
    "SELECT * FROM events WHERE drive_id = ? ORDER BY t ASC",
    [driveId],
  );
  return rows.map(toEvent);
}

/** Total drives + average score (for the dashboard gauge). */
export async function getDriveStats(): Promise<DriveStats> {
  const db = await getDb();
  const row = await db.getFirstAsync<{ count: number; avg: number | null }>(
    "SELECT COUNT(*) AS count, AVG(score) AS avg FROM drives",
  );
  return {
    totalDrives: row?.count ?? 0,
    averageScore: row?.avg != null ? Math.round(row.avg) : 0,
  };
}

/** Delete a single drive (its events cascade away via the FK). */
export async function deleteDrive(id: string): Promise<void> {
  const db = await getDb();
  await db.runAsync("DELETE FROM drives WHERE id = ?", [id]);
}

/** Wipe everything (handy for dev / a "clear history" action). */
export async function clearAllDrives(): Promise<void> {
  const db = await getDb();
  await db.execAsync("DELETE FROM events; DELETE FROM drives;");
}
